### ISSUE TITLE
Please add me to the garden

### ISSUE THREAD

**Issue by kiok46** [kivy-garden/kivy-garden.github.io#109]
I have a widget that I would like to contribute to kivy garden.
You can find it here. https://github.com/kiok46/swipetodelete

**Comment by dessant** [comment]
Looks promising, thanks for taking the time to contribute.
Please transfer the repo to me so i can move it to garden.
`Transfer ownership` at the bottom of this page https://github.com/kiok46/swipetodelete/settings.

**Comment by dessant** [comment]
You should have write access to https://github.com/kivy-garden/garden.swipetodelete.

Thanks again and happy coding!

**Comment by kiok46** [comment]
Thank you for accepting. I will contribute again. :)
