### ISSUE TITLE
How to use kivy-garden on mac

### ISSUE THREAD

**Issue by Jayuda** [kivy-garden/kivy-garden.github.io#110]
Hello Mr,
i have install kivy on mac with this tutorial : http://kivy.org/docs/installation/installation-macosx.html#installing-modules

So, all package python kivy location at `/Applications/Kivy.app/Contents/ ....`
i was install kivy-garden with : `kivy -m pip install kivy-garden`

How i call garden to install other package ? i use : `garden install XXX` not recognise.  

Sorry if this question is very low knowledge. Thanks

**Comment by akshayaurora** [comment]
can you try 

kivy -m garden install <package_name>

**Comment by Jayuda** [comment]
i have try Mr @akshayaurora , the result show error : 
`$ kivy -m garden install filebrowser
/Applications/Kivy.app/Contents/Resources/python: No module named garden.__main__; 'garden' is a package and cannot be directly executed`

**Comment by dessant** [comment]
@Jayuda please reopen here if the issue is still present: https://github.com/kivy-garden/garden/issues.
