### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by sdementen** [kivy-garden/kivy-garden.github.io#112]
Link for a merged garden PR or a proposed new flower:
https://github.com/sdementen/hotkeybehavior

(I am not sure how to proceed to add this package, is it the proper way ?)

**Comment by sdementen** [comment]
some questions before joining kivy garden:
- how can I use a setup.py (for a.o. dependencies) ?
- how can I package/release the flower ?
- what is installed when doing a "garden install ..." ? the whole repo ?
- how can I add tests in the repo ? (i do not see lot of tests in the kivy-garden repos)

Is it possible to release the package in a standard way (own repo, PYPI upload, etc) while being searchable and installable via the garden command ?

**Comment by dessant** [comment]
If you rename `hotkey.py` to `__init__.py` the flower should work and install properly.
We do not support installing packages hosted on pypi with the garden tool.

The repo will have to be transferred to me or someone else from the team so we can move it further to kivy-garden, see the bottom of repo settings.

Thanks a lot for your contribution.

**Comment by sdementen** [comment]
hello,
I have transferred the repo to you and rename the hotkey.py file to
__init__.py.
Keep me posted if anything more should be done and tx for maintaining the
garden !

**Comment by dessant** [comment]
@sdementen, once you accept the invitation you should have write access to https://github.com/kivy-garden/garden.hotkeybehavior. :+1:
