### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by yoelk** [kivy-garden/kivy-garden.github.io#115]
Link for a merged garden PR or a proposed new flower:
https://github.com/yoelk/garden.multichoicetogglebutton

Hi,
I tried running the pep8checker upon commit, but it couldn't run the script.
First I gave me the error:
`.git/hooks/pre-commit: line 17: 
    Kivy Git Pre-Commit Hook to Enforce Styleguide
    ==============================================

    This script is not supposed to be run directly.
    Instead, copy it to your kivy/.git/hooks/ directory, call it pre-commit
    and make it executable.

    If you attempt to commit, git will run this script, which in turn will run
    the styleguide checker over your code and abort the commit if there are any
    errors. If that happens, please fix & retry.

    To install::

        cp kivy/tools/pep8checker/pre-commit.githook .git/hooks/pre-commit
        chmod +x .git/hooks/pre-commit
    : No such file or directory
    .git/hooks/pre-commit: line 19: import: command not found
    from: can't read /var/mail/os.path
    from: can't read /var/mail/subprocess
    .git/hooks/pre-commit: line 23: syntax error near unexpected token ('
    .git/hooks/pre-commit: line 23: curdir = dirname(abspath(__file__))'
     (1)`

And when I followed (these instructions) [https://github.com/kivy/kivy/issues/3893] I got the following error:
`Traceback (most recent call last):
  File ".git/hooks/pre-commit", line 33, in <module>
    import kivy
ImportError: No module named kivy
 (1)`

If you can help me get it to work, I'd appreciate it.

I hope you like my flower,
Joel

**Comment by dessant** [comment]
Thanks. :+1: The repo will have to be transferred to me or someone else from the team, see the bottom of repo settings.

**Comment by yoelk** [comment]
Great! I just did.
Please tell me if something else is necessary.

Joel

**Comment by dessant** [comment]
That's it, you should have write access to https://github.com/kivy-garden/garden.multichoicetogglebutton once the invitation is accepted, thanks a lot.
