### ISSUE TITLE
A new flower out there

### ISSUE THREAD

**Issue by unjuan** [kivy-garden/kivy-garden.github.io#116]
Greetings
I made a widget for kivy and I would appreciate an expert's opinion.
It might be of interest to you.
https://github.com/unjuan/Rotabox

Thanks in advance
unjuan

**Comment by akshayaurora** [comment]
dude/dudete this is awesome!!!

**Comment by dessant** [comment]
@unjuan, would you like to transfer the repo to kivy-garden and become a member?

**Comment by unjuan** [comment]
@akshayaurora, thanks man (excuse the delay - I somehow missed your message)

@dessant, yes, of course. What do I need to do?

**Comment by dessant** [comment]
Transfer it to me, at the bottom of repo settings, then i'll pass it on to kivy-garden.

**Comment by dessant** [comment]
@unjuan, once the invitation is accepted, you will become a kivy-garden member and have write access to https://github.com/kivy-garden/garden.rotabox.

Welcome and thank you for your neat work. :tropical_drink:
