### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by ophermit** [kivy-garden/kivy-garden.github.io#117]
Link for a merged garden PR or a proposed new flower:
https://github.com/ophermit/xpopup

**Comment by dessant** [comment]
The repo will have to be transferred to me or someone else from the team, see the bottom of repo settings.

Thanks for taking the time to contribute. :+1:

**Comment by ophermit** [comment]
Request to transfer has been sent. Thanks for attention!

**Comment by dessant** [comment]
@ophermit, you've been invited to become a kivy-garden member, once accepted, you should have write access to https://github.com/kivy-garden/garden.xpopup.
