### ISSUE TITLE
New garden flower is here!

### ISSUE THREAD

**Issue by rafalo1333** [kivy-garden/kivy-garden.github.io#118]
Add me to the Kivy Garden please.

I've created simple bar module. It has Bar widget included, which enables the developers to easily create animated statistic bars. I will add even more features in the future.

https://github.com/rafalo1333/garden.bar

Widget has a well documented API and is ready to go :)

**Comment by dessant** [comment]
The repo has been transferred and you should have write access, thanks a lot.
https://github.com/kivy-garden/garden.bar
