### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by antocuni** [kivy-garden/kivy-garden.github.io#120]
Hi, I wrote this new widget which I think might be a good candidate for the kivy garden :)
https://github.com/antocuni/garden.xcamera

**Comment by dessant** [comment]
@antocuni, thanks a lot for your work, please transfer the repo to me and i'll pass it to garden.

**Comment by dessant** [comment]
It was moved to https://github.com/kivy-garden/garden.xcamera and you should have write access to it. :dancer:
