### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by wackazong** [kivy-garden/kivy-garden.github.io#123]
Link for a merged garden PR or a proposed new flower:
https://github.com/wackazong/garden.touchgraph

**Comment by dessant** [comment]
@wackazong, please transfer the repo to me so i can pass it to garden.

**Comment by dessant** [comment]
You should have push rights once you accept the invitation: https://github.com/kivy-garden/garden.touchgraph.
Welcome and thanks for your contribution. <3
