### ISSUE TITLE
Possible Kivy Garden Module

### ISSUE THREAD

**Issue by samocooper** [kivy-garden/kivy-garden.github.io#126]
Hi there,

Created a widget for displaying Numpy Matrices as images using a color map. Using kivy at the moment for creating an App for microscopy image analysis, found it super easy, and definitely something allot of academics could use, a few simple widgets like this and more plotting especially interactive plotting widgets could definitely uptake. Would been keen to get involved but not the greatest coder ever. Would anyone be able to check out the code in my repository and see if it's up to scratch/something you'd want in garden?

Best,
Sam  

https://github.com/samocooper/numpy_image

**Comment by KeyWeeUsr** [comment]
I'm sorry that no one got in touch with you sooner. Personally I just haven't noticed the opened issue properly.

While the description sounds nice, I haven't found any visual representation of what does it do, nor when trying locally the dependencies are resolved (missing `skimage`, currently known as `scikit-image` for start). And other less important issues such as proper pep8 formatting, documentation for the functions and proper package name (`garden.<package>`). On the other hand, you don't need to use that to output an image as you can just load the image and display it in the Kivy Image widget.

If you still feel that you want to include it to the garden, please fix the issues mentioned above and let us know.
