### ISSUE TITLE
Garden gallery screenshots

### ISSUE THREAD

**Issue by KeyWeeUsr** [kivy-garden/kivy-garden.github.io#130]
Hello, kivy-garden users ( @kivy-garden/notification )!

As you've may noticed, there has been a little change in the garden [website](https://kivy-garden.github.io) that made it possible to show garden widgets in a single place in a more sane way than forcing a potential user to actually click & read everything (if no screenshot available) in each repository (which is just time-consuming) to get a clue what is it actually about - a gallery.

The gallery automatically fetches a few things:
* Name (evetything after `garden.`)
* URL (of the repository, so that a user can easily find it)
* Square screenshot (locally via the URL + some suffix)

I've created a custom team which will be deleted in a month or sooner only to contact you all at once. This way I'd like you to consider making a single small square screenshot in the required location (and/or move or replace the current one) describing your flower in the best way possible, which you think will interest your (new) users.

I chose the file name to be `screenshot.png` as there already were some screenshots available, although some not in the quite fitting shape (square). You may propose other name for the screenshot if you don't want the name to be colliding with your current state of repositories, but a change will be most likely accepted if at least 3/5 of you agree on one.

The screenshot needs to fit these restrictions to be displayed correctly:
* located in the root of your repository under `screenshot.png` name
* min. size of 128 x 128 px
* PNG file

Hopefully you find the change useful ^^

_Note: if you don't have any repository in garden, please ignore this notification._

**Comment by wackazong** [comment]
Done.

**Comment by matham** [comment]
I'm not sure it's a good idea to have such a low res image as THE
screenshot image in the root directory. I think it's preferred that the
main image be very high resolution so that we can see what the flower does.

Could you not resize the image for the website so that it becomes 128x128?

**Comment by KeyWeeUsr** [comment]
@matham The image is resized and scaled properly with css that's not the issue. The size mentioned is meant in the meaning "at least that", so that it actually is visible in the gallery, but also quickly loaded by the browser (25 images in total for a single page). I should have stated it.

**Comment by KeyWeeUsr** [comment]
Closed with the recent batch adding of screenshot. There are still 10 flowers (1 empty) which don't have the screenshots. Most of them either don't do anything visual or require gif/video to actually present the behavior, so feel free to update them.
