### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by manthansharma** [kivy-garden/kivy-garden.github.io#133]
Link for a merged garden PR or a proposed new flower:
https://github.com/kivy-garden/garden.xpopup/pull/1

**Comment by KeyWeeUsr** [comment]
ref https://github.com/kivy-garden/kivy-garden.github.io/issues/132#issuecomment-288502226

If @ophermit is ok with adding you to his repository, I think he has the rights in the organization to add you to his repository as another member who has committing, merging and other admin rights.
