### ISSUE TITLE
preparing for new entry for garden: question concerning separation

### ISSUE THREAD

**Issue by JohnAD** [kivy-garden/kivy-garden.github.io#134]
I'm prepping a new entry for kivy-garden called `FixedLayout`. It allows one to establish fixed virtual pixel dimensions (such as 1920x1080 or 640x480) for an app and then use simple (virtual) pixel coordinates that automatically scale to the real-world dimension and aspect-ratio of any real-world device. (`fixed_pos`, `fixed_size` and `fixed_offset` as opposed to `pos_hint` and `size_hint`.)

But right now this library also has three new widgets that only function under FixedLayout. Kivy-garden emphasizes the "do one thing well" mantra. With that in mind which would be preferred?

1. Make one "flower" in kivy-garden. Document both the layout and the subtending widgets.
2. Put just the layout of FixedLayout in one flower. Put each of the other three widgets in separate flowers and **explicitly** document that they are fully dependent on FixedLayout to operate.

I'm happy to do either. Just let me know. Thanks!

**Comment by JohnAD** [comment]
If option 1, then the import statements might look like:

    from kivy.garden.fixedlayout import FixedLayout, FixedPopup,  FixedRadioButton, \
        FixedSimpleMenu, FixedSimpleMenuItem

If option 2, then the import statements might look like:


    from kivy.garden.fixedlayout import FixedLayout
    from kivy.garden.fixedlayout.popup import FixedPopup
    from kivy.garden.fixedlayout.radiobutton import FixedRadioButton
    from kivy.garden.fixedlayout.simplemenu import FixedSimpleMenu, FixedSimpleMenuItem

etc.

**Comment by KeyWeeUsr** [comment]
Let's say it'd be better to have them in separate modules(the second option) as the classes in such case might become bigger e.g. like it's with `RecycleView` in [`kivy/kivy/uix`](https://github.com/kivy/kivy/tree/master/kivy/uix), but the structure i.e. if you put it into folders with `__init__.py` or just into files is up to you.

Also, how does it differ from a `FloatLayout` + `size = (x, y)`, where `x` and `y` can use [`metrics`](https://kivy.org/docs/api-kivy.metrics.html#dimensions) i.e. `dp` or `sp`?

**Comment by JohnAD** [comment]
The purpose of `dp` (and metrics in general) is to make the screen elements not dependent on real-world density and size of the screen. That way a 4cm box is a 4cm box regardless of the device being shown on. This is fantastic tool for making apps responsive.

This library does the opposite. It scales the screen elements ignoring real-world size. So, if an app is 1920x1080 and a 1920x1080 image is shown, it perfectly fits the whole screen whether it is a tiny 320x320 android watch or a large 4k 18" tablet. It also takes into account screen ratios. So a square watch might have black bars on the top/bottom. But a tall phone held sideways might have black bars on the sides.

Certainly, one could manipulate the `dp` by overriding *KIVY_METRICS_DENSITY* and then write a child class that handles the dp offsets for centering in various ratios. At that point, you have pretty much written this same library. :) In fact, my library inherits from FloatLayout.

When I first started writing this library, I seriously considered simply adding a new metric to the Kivy core instead. Perhaps 'tp' for *translated point* and add a new list object for the virtual size. But that appeared to be far greater work than I wanted to take on.

**Comment by KeyWeeUsr** [comment]
@JohnAD any progress with this issue?
