### ISSUE TITLE
zbarcam flower to the garden

### ISSUE THREAD

**Issue by AndreMiras** [kivy-garden/kivy-garden.github.io#136]
I've just created a real-time QR Code and Barcode scanner [AndreMiras/garden.zbarcam](https://github.com/AndreMiras/garden.zbarcam) and I would love to make it part of the garden. It uses [ZBar/ZBar](https://github.com/ZBar/ZBar) and `kivy.uix.camera`.

I use it for [PyWallet](https://github.com/AndreMiras/PyWallet), a cross platform Ethereum wallet of mine.
zbarcam flower is still in a early stage of development, but I like the release early release often philosophy. The earlier I can get feedback, the better.

I could run it successfully on Linux and next up will be Android. So I planned to pick up this issue in the coming weeks https://github.com/kivy/python-for-android/issues/854.

**Comment by AndreMiras** [comment]
It's now running perfectly on Android since last release (20171019).
Please let me know if I need to do anything else to be integrated to the garden.

**Comment by dessant** [comment]
@AndreMiras, sorry for the late reply. Please transfer the repo to me so we can add it to the garden.

**Comment by AndreMiras** [comment]
Hi @dessant I've just made the transfer

**Comment by AndreMiras** [comment]
I'm proud to be part of the garden: https://github.com/kivy-garden/garden.zbarcam
Thanks!

**Comment by dessant** [comment]
Thanks for your contribution! 🎉
