### ISSUE TITLE
Please add me to the Kivy Garden

### ISSUE THREAD

**Issue by myasiny** [kivy-garden/kivy-garden.github.io#139]
Kivy garden flower providing a widget for sending e-mails from a form on app:
[ContactForm](https://github.com/myasiny/garden.contactform)

**Comment by dessant** [comment]
Looks great! Please transfer the repository to me so it can be moved to the org.

**Comment by myasiny** [comment]
Done, transfer requested 👍

**Comment by dessant** [comment]
You should have write access to https://github.com/kivy-garden/garden.contactform once the invitation is accepted. Thanks a lot for your contribution!
