### ISSUE TITLE
kivy garden  requests.exceptions.SSLError

### ISSUE THREAD

**Issue by electromc2** [kivy-garden/kivy-garden.github.io#140]
When I try  "garden install xpopup" or any garden install for that matter I get the following error
Running on the latest macos(OSX)

Any ideas
Thanks in advance
Terry
raise SSLError(e, request=request)
 requests.exceptions.SSLError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /kivy-garden/garden.xpopup/archive/master.zip (Caused by SSLError(SSLError(1, u'[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)'),))

**Comment by electromc2** [comment]
Thanks for the reply dolang. Yes i have tried that already. Spent a couple of days trying everything that I could find. Run out of ideas.

**Comment by dolang** [comment]
Well, that's highly unusual.

Anyway, as it says, the error is an `requests.exceptions.SSLError` from the external `requests` package. You might be able to dig something up by looking through their [GitHub repository](https://github.com/requests/requests).

Also, here's the [relevant section from the requests documentation](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification). By the way, you can test it yourself by doing:
```
$ python
>>> import requests
>>> requests.get('https://github.com')
```

**Comment by AndreMiras** [comment]
I would also say it's an issue with the setup. Feel free to reopen if you think it's not
