### ISSUE TITLE
Please add this to Kivy Garden

### ISSUE THREAD

**Issue by gottadiveintopython** [kivy-garden/kivy-garden.github.io#158]
https://github.com/gottadiveintopython/draggable

**Comment by matham** [comment]
I'm a bit uncomfortable that it basically has the same name as the `drag_n_drop` flower. Could you use another name? I would rather that people don't confuse it with `drag_n_drop`. Especially since it's `drag_n_drop2`, which may give the impression that this is a latter version of it.

**Comment by gottadiveintopython** [comment]
got it. I'll fix it soon.

**Comment by gottadiveintopython** [comment]
@matham I fixed. Is it all fine?

**Comment by matham** [comment]
Yeah, if you want to transfer it to me I'll transfer it to garden.

**Comment by gottadiveintopython** [comment]
Thanks, I asked to tranfer the repository :)

**Comment by matham** [comment]
Ok, done: https://github.com/kivy-garden/draggable. And you should have write access to it. Lemme know if you don't.
