### ISSUE TITLE
Garden licensing

### ISSUE THREAD

**Issue by kived** [kivy-garden/kivy-garden.github.io#56]
Given the nature of Kivy Garden, shouldn't all the garden widgets have licenses? Many do not (based on checking for a LICENSE file or a license reference in README.md) - this means you cannot use this code. Any code uploaded here without an explicit license has an implicit copyright (in all but a small number of countries) with NO license, which means that no one can copy, modify, distribute or reuse this code ("All Rights Reserved"). That's right - technically, you're not even allowed to download the code from GitHub.

http://www.infoworld.com/d/open-source-software/github-needs-take-open-source-seriously-208046

But there wouldn't be much point to uploading a widget to the garden if you didn't expect someone else to use it. I think that specified licensing (preferably via a LICENSE file) should be a requirement for adding a widget to the garden, or at least the garden submission guidelines should specify that any code added to the garden is automatically licensed under MIT (same as Kivy) unless otherwise specified (via a LICENSE file).

Oh, and the garden tool itself doesn't have a LICENSE file either. ;) Though it is specified as MIT in the setup.py, licensing should be a tad more obvious than that.

**Comment by dessant** [comment]
Repos needing permission for releasing under the MIT license:
https://github.com/kivy-garden/garden.segment
https://github.com/kivy-garden/garden.timeline
https://github.com/kivy-garden/garden.gauge
https://github.com/kivy-garden/garden.roulettescroll
https://github.com/kivy-garden/garden.roulette
https://github.com/kivy-garden/garden.datetimepicker
https://github.com/kivy-garden/garden.tickline
https://github.com/kivy-garden/garden.moretransitions

**Comment by dessant** [comment]
Remaining ones:
https://github.com/kivy-garden/garden.segment
https://github.com/kivy-garden/garden.gauge
https://github.com/kivy-garden/garden.moretransitions

**Comment by dessant** [comment]
All garden repositories are under MIT now.
