### ISSUE TITLE
Please add me to the garden :)

### ISSUE THREAD

**Issue by PhilippeTrounev** [kivy-garden/kivy-garden.github.io#81]
:) Thank you!

**Comment by gustavklopp** [comment]
The last person admitted to The Garden was in May apparently :( 10 months ago. 
It's spring soon, so I keep hope alive for the garden...

**Comment by tito** [comment]
People asking here is not the way it should be done, unfortunately. See the section "Transferring repository" in http://kivy-garden.github.io/

**Comment by akshayaurora** [comment]
Invitation sent.
