### ISSUE TITLE
Please add me to the garden

### ISSUE THREAD

**Issue by dennyb87** [kivy-garden/kivy-garden.github.io#90]
Hi I am Denny and I am a passionate developer in love with python. I made a widget, and I would like to add it to the garden, that's it.

Thanks in andvance!

**Comment by dessant** [comment]
Hi, welcome to the garden. :) I have added you, what is your widget's name?

**Comment by dennyb87** [comment]
it called "androidtabs", I'm working on the code to improve it, and when ready I would publish it in the garden if possible. https://github.com/dennyb87/androidtabs

**Comment by dessant** [comment]
https://github.com/kivy-garden/garden.androidtabs was created, you should have write access to it. Thanks for your contribution. ;)

**Comment by dennyb87** [comment]
Thank you very much :)
