### ISSUE TITLE
Create another repository for me

### ISSUE THREAD

**Issue by martinsik** [kivy-garden/kivy-garden.github.io#94]
While working on [garden.desktopvideoplayer](https://github.com/kivy-garden/garden.desktopvideoplayer) I had to work with creating context menus and realised that I could split it into two smaller projects. One is the video player and the second one is a general set of classes for simple creating context menus (maybe called garden.contextmenu):
![screen shot 2015-08-05 at 18 34 02](https://cloud.githubusercontent.com/assets/238765/9091649/b0dd369a-3ba1-11e5-9c19-58acd3d1a8b0.png)
Everything is easily customizable so you can add various controls right into the menu.
![screen shot 2015-08-05 at 18 34 37](https://cloud.githubusercontent.com/assets/238765/9091817/8dfe72d2-3ba2-11e5-9e18-936729ea5a39.png)
I'd also like to enhance it with classes to easily design application top menu bars which I think could work well also on mobile devices.

**Comment by dessant** [comment]
Cool, cool, cool :+1: . What is the flower's name?

**Comment by martinsik** [comment]
Thanks! Is `garden.contextmenu` ok?

**Comment by dessant** [comment]
Done, happy coding. :)

**Comment by martinsik** [comment]
@dessant I think I have the same problem as last time:

```
remote: Permission to kivy-garden/garden.contextmenu.git denied to martinsik.
fatal: unable to access 'https://github.com/kivy-garden/garden.contextmenu.git/': The requested URL returned error: 403
```

We solved this on IRC, there was something wrong with permissions or what.

**Comment by dessant** [comment]
@martinsik :D, i forgot again to add the repo to the team.

**Comment by dessant** [comment]
Done, sorry for the hiccup.
